version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only
    rebase-strategy: auto
    groups:
      all-cargo-deps:
        patterns:
          - "*"
