version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only
    rebase-strategy: auto
    group:
        name: "all-cargo-dependencies"
        patterns:
            - "*"
