[workspace]
members = ["snxcore", "snxctl", "snx-rs", "snx-rs-gui"]
resolver = "2"

[workspace.package]
version = "3.1.1"
license = "AGPL-3.0"
edition = "2021"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Rust client for Checkpoint VPN tunnels"
readme = "README.md"
repository = "https://github.com/ancwrd1/snx-rs"
keywords = ["snx", "vpn", "ipsec"]
publish = false
rust-version = "1.79"

[profile.release]
panic = "abort"

[profile.lto]
inherits = "release"
strip = true
lto = true
codegen-units = 1
