[package]
name = "snx-rs"
version = "1.0.0-rc.2"
license = "AGPL-3.0"
edition = "2021"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Rust client for Checkpoint VPN tunnels"
readme = "README.md"
repository = "https://github.com/ancwrd1/snx-rs"
keywords = ["snx", "vpn", "ipsec"]
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[features]
default = []
tray-icon = ["dep:ksni", "dep:which"]
webkit2gtk = ["dep:webkit2gtk", "dep:gtk"]

[dependencies]
isakmp = { git = "https://github.com/ancwrd1/isakmp.git" }
pest = "2"
pest_derive = "2"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-native-tls = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "fs", "io-util", "process", "signal"] }
tokio-util = "0.7"
reqwest = { version = "0.11", features = ["native-tls"] }
futures = "0.3"
bytes = "1"
hex = "0.4"
tun = { version = "0.6", features = ["async"] }
ipnet = {  version = "2", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
base64 = "0.22"
tracing = { version = "0.1", features = [] }
tracing-subscriber = "0.3"
async-trait = "0.1"
async-recursion = "1"
rand = "0.8"
directories-next = "2"
chrono = { version = "0.4", features = ["serde"] }
passterm = "2"
which = { version = "6", optional = true }
opener = { version = "0.6"}
enum-as-inner = "0.6"
num-traits = "0.2"
parse_int = "0.6"
parking_lot = "0.12"
byteorder = "1"
regex = "1"
once_cell = "1"
webkit2gtk = { version = "2", optional = true, features = ["v2_6", "v2_16", "v2_30"] }
gtk = { version = "0.18", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
ksni = { version = "0.2", optional = true }
zbus = { version = "3", default-features = false, features = ["tokio"] }
secret-service = {  version = "3", features = ["rt-tokio-crypto-rust"] }
