[package]
name = "snx-rs"
version = "0.4.0"

edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
pest = "2"
pest_derive = "2"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-native-tls = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "fs", "io-util", "process", "signal"] }
tokio-util = "0.7"
reqwest = { version = "0.11", features = ["native-tls"] }
futures = "0.3"
bytes = "1"
hex = "0.4"
tun = { version = "0.5", features = ["async"] }
ipnet = "2"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
base64 = "0.21"
tracing = { version = "0.1", features = [] }
tracing-subscriber = "0.3"
async-trait = "0.1"
rand = "0.8"
directories-next = "2"
chrono = { version = "0.4", features = ["serde"] }

[target.'cfg(target_os = "linux")'.dependencies]
zbus = "3"
